service: newrelic-otlp-issue
package:
  individually: true

provider:
  name: aws
  runtime: provided.al2023
  region: ca-central-1
  architecture: arm64
  deploymentMethod: direct
  timeout: 30
  layers:
    - arn:aws:lambda:ca-central-1:901920570463:layer:aws-otel-collector-arm64-ver-0-90-1:1
  environment:
    OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yaml
    NEW_RELIC_LICENSE_KEY: "Place NewRelic API Key here"
    NEW_RELIC_OPENTELEMETRY_ENDPOINT: https://otlp.nr-data.net

functions:
  api:
    handler: bootstrap
    memorySize: 128
    package:
      artifact: target/lambda/newrelic-otlp-issue/bootstrap.zip
    events:
      - httpApi: "*"
