service: newrelic-otlp-issue
frameworkVersion: ^3.38.0
useDotenv: true

provider:
  name: aws
  runtime: provided.al2023
  region: us-west-2
  architecture: arm64
  # deploymentMethod: direct
  timeout: 10
  logRetentionInDays: 14
  layers:
    - arn:aws:lambda:us-west-2:901920570463:layer:aws-otel-collector-arm64-ver-0-90-1:1
  environment:
    OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yaml
    NEW_RELIC_LICENSE_KEY: ${env:NEW_RELIC_LICENSE_KEY}
    NEW_RELIC_OPENTELEMETRY_ENDPOINT: ${env:NEW_RELIC_OPENTELEMETRY_ENDPOINT}

package:
  individually: true

functions:
  api:
    handler: bootstrap
    memorySize: 256
    package:
      artifact: target/lambda/newrelic-otlp-issue/bootstrap.zip
    events:
      - httpApi: "*"
